### ISSUE TITLE
Maintenance of hivelocity-client-go

### ISSUE THREAD

**Issue by guettli** [hivelocity/cluster-api-provider-hivelocity#77]
/kind feature

**Describe the solution you'd like**

Up to now it is not clear how the [hivelocity-client-go](https://github.com/hivelocity/hivelocity-client-go) will get maintained in the future.

**Comment by aniruddha2000** [comment]
We can think of structuring the project, and add test later, I can collaborate if it has a higher priority and needs more hand

**Comment by guettli** [comment]
I think we can close this. Time will tell.
